"""add freelancer_id to tasks

Revision ID: 2d66501e76ce
Revises: c3d8ca54c056
Create Date: 2026-07-09 22:04:04.536091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d66501e76ce'
down_revision: Union[str, Sequence[str], None] = 'c3d8ca54c056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('freelancer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['freelancer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'freelancer_id')
    # ### end Alembic commands ###
