"""Add proposed_budget to applications

Revision ID: 4572d813c929
Revises: 2dac078a509e
Create Date: 2026-07-24 17:57:21.395419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4572d813c929'
down_revision: Union[str, Sequence[str], None] = '2dac078a509e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('proposed_budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'proposed_budget')
    # ### end Alembic commands ###
