"""Auto migration

Revision ID: 4dec3db5738d
Revises: 
Create Date: 2026-06-16 21:45:21.936492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4dec3db5738d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='applicationstatus'), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('freelance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['freelance_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.add_column('tasks', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('tasks', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('client_id', sa.Integer(), nullable=True))
    op.alter_column('tasks', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=2000),
               nullable=True)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_location'), 'tasks', ['location'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.drop_constraint(op.f('tasks_ibfk_1'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_ibfk_2'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['client_id'], ['id'])
    op.drop_column('tasks', 'user_id')
    op.drop_column('tasks', 'created_at')
    op.drop_column('tasks', 'localisation')
    op.drop_column('tasks', 'is_permanent')
    op.drop_column('tasks', 'freelance_id')
    op.drop_column('tasks', 'category_type')
    op.drop_column('tasks', 'deadline')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_client', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_freelancer', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=255), nullable=True))
    op.drop_index(op.f('email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'is_verified_pro')
    op.drop_column('users', 'experience_years')
    op.drop_column('users', 'verification_status')
    op.drop_column('users', 'name')
    op.drop_column('users', 'role')
    op.drop_column('users', 'skills_list')
    op.drop_column('users', 'user_mode')
    op.drop_column('users', 'password')
    op.drop_column('users', 'portfolio_url')
    op.drop_column('users', 'prof_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prof_title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('portfolio_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('user_mode', mysql.ENUM('simple', 'pro'), server_default=sa.text("'simple'"), nullable=True))
    op.add_column('users', sa.Column('skills_list', mysql.TEXT(), nullable=True))
    op.add_column('users', sa.Column('role', mysql.ENUM('client', 'freelance', 'admin'), nullable=False))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('verification_status', mysql.ENUM('none', 'pending', 'approved', 'rejected'), server_default=sa.text("'none'"), nullable=True))
    op.add_column('users', sa.Column('experience_years', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_verified_pro', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'location')
    op.drop_column('users', 'is_freelancer')
    op.drop_column('users', 'is_client')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'full_name')
    op.add_column('tasks', sa.Column('deadline', sa.DATE(), nullable=True))
    op.add_column('tasks', sa.Column('category_type', mysql.ENUM('simple', 'pro'), server_default=sa.text("'pro'"), nullable=True))
    op.add_column('tasks', sa.Column('freelance_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('is_permanent', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('localisation', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('tasks', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('tasks', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_ibfk_2'), 'tasks', 'users', ['freelance_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('tasks_ibfk_1'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_location'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.alter_column('tasks', 'description',
               existing_type=sa.String(length=2000),
               type_=mysql.TEXT(),
               nullable=False)
    op.drop_column('tasks', 'client_id')
    op.drop_column('tasks', 'location')
    op.drop_column('tasks', 'price')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
