"""Add bio and profile_image to users

Revision ID: ac2839c4ab12
Revises: f3a9c12d4e5b
Create Date: 2026-07-23 10:43:42.825589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2839c4ab12'
down_revision: Union[str, Sequence[str], None] = 'f3a9c12d4e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_reviewee_id_users'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['reviewee_id'], ['id'])
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'bio')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reviews_reviewee_id_users'), 'reviews', 'users', ['reviewee_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
