"""add_feedback_table

Revision ID: dd691ca24cf8
Revises: 4572d813c929
Create Date: 2026-07-24 18:16:22.264631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd691ca24cf8'
down_revision: Union[str, Sequence[str], None] = '4572d813c929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('BUG', 'FEATURE', 'GENERAL', 'OTHER', name='feedbackcategory'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ANSWERED', 'CLOSED', name='feedbackstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('replied_by', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['replied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_category'), 'feedbacks', ['category'], unique=False)
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_feedbacks_status'), 'feedbacks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_status'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_category'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
